package:
  name: cvxopt
  version: "1.1.8"

source:
  fn: cvxopt-1.1.8.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxopt/cvxopt-1.1.8.tar.gz
  md5: d4ff0a0e51aba93f838a70302a088eea

  patches:
    - setup.py.patch

requirements:
  build:
    - nomkl
    - openblas
    - python
    - setuptools

  run:
    - nomkl
    - openblas
    - python

build:
  number: 105

  features:
    - nomkl
    - openblas

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GNU General Public License v3 (GPLv3)
  summary: 'Convex optimization package'
