package:
  name: openblas
  version: 0.2.18

source:
  fn: openblas-0.2.18.tgz
  url: http://github.com/xianyi/OpenBLAS/tarball/v0.2.18

build:
  number: 101

  features:
    - nomkl

  track_features:
    - openblas

requirements:
  build:
    - nomkl

  run:
    - nomkl
    - libgcc

about:
  home: http://xianyi.github.io/OpenBLAS/
  license: BSD
