package:
  name: sima
  version: "1.3.0"

source:
  fn: sima-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/s/sima/sima-1.3.0.tar.gz
  md5: 19766fd696ace43ba3d723b0eeceeea6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sima = sima:main
    #
    # Would create an entry point called sima that calls sima.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - cython
    - numpy >=1.8
    - scipy >=0.13.0
    - scikit-image >=0.9.3
    - shapely >=1.2.14
    - scikit-learn >=0.11
    - pillow >=2.6.1
    - future >=0.14

  run:
    - python
    - numpy >=1.8
    - scipy >=0.13.0
    - scikit-image >=0.9.3
    - shapely >=1.2.14
    - scikit-learn >=0.11
    - pillow >=2.6.1
    - future >=0.14

test:
  # Python imports
  imports:
    - sima
    - sima.misc
    - sima.motion
    - sima.motion.tests
    - sima.segment
    - sima.segment.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.losonczylab.org/sima/
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Software for analysis of sequential imaging data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
