package:
  name: numpy
  version: 1.11.0b1

source:
  url: https://github.com/numpy/numpy/archive/v1.11.0b1.tar.gz
  fn: numpy-1.11.0b1.tar.gz

requirements:
  build:
    - python
    - cython
    - nomkl
    - openblas 

  run:
    - python
    - openblas

build:
  number: 100

  features:
    - nomkl
    - openblas

about:
  home: https://www.numpy.org
  license: PSF
